resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: GitHub                            # <-- replace with your integration DONE 
      path: HKTFrog/jfrog-pipelines-docker-sample    # <-- replace with your repository name DONE 
      branches:
        include: master

  - name: dbp_image
    type: Image
    configuration:
      registry: Artifactory                             # <-- replace with your artifactory integration DONE
      sourceRepository: dev-docker-local                # <-- required if registry is Artifactory DONE 
      imageName: coe.jfrog.io/dev-docker-local/dbp      # < -- replace with your image path and name DONE 
      imageTag: latest
      autoPull: true
      
  - name: dbp_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: dbp_build
      buildNumber: 1    

  - name: dbp_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: dbp_build
      buildNumber: 1
      
  - name: cron_trigger_docker
    type: CronTrigger
    configuration:
      interval: '0 2 * * *'       
      
pipelines:
  - name: Docker_Quickstart
    configuration:
      jfrogCliVersion: 2  
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: coe.jfrog.io/dev-docker-local/dbp  # replace with your image path and name DONE 
          dockerImageTag: ${run_number}
          inputResources:
            - name: dbp_repo
            - name: cron_trigger_docker
          integrations:
            - name: Artifactory                            # <-- replace with your artifactory integration DONE 
        execution:
          onStart:
              # - msg="Run description updated from step $step_id"
              # - update_run_description "$msg"  
              - update_run_description "Add custom text for every run. Example - Build and push Docker image to Artifactory."

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: dev-docker-local   
          integrations:
            - name: Artifactory                            # <-- replace with your artifactory integration DONE 
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image           

      - name: publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: dbp_build_info          

      - name: promote_dbp_build
        type: PromoteBuild
        configuration:
          targetRepository: dev-docker-local
          integrations:
            - name: Artifactory
          inputResources:
            - name: dbp_build_info
          outputResources:
            - name: dbp_promoted_build_info
